export const UserActions = Object.freeze({
  FETCH_ALL: "users/FETCH_ALL",
  FETCH: "users/FETCH",
  CREATE: "users/CREATE",
  UPDATE: "users/UPDATE",
  UPDATE_AVATAR: "users/UPDATE_AVATAR",
  DELETE: "users/DELETE",
  RESTORE: "users/RESTORE",
  PERMANENTLY_DELETE: "users/PERMANENTLY_DELETE"
});

export const SurveyActions = Object.freeze({
  FETCH_ALL: "surveys/FETCH_ALL",
  FETCH: "surveys/FETCH",
  FETCH_BY_SLUG: "surveys/FETCH_BY_SLUG",
  CREATE: "surveys/CREATE",
  CREATE_QUESTION_GROUP: "surveys/CREATE_QUESTION_GROUP",
  CREATE_QUESTION: "surveys/CREATE_QUESTION",
  UPDATE: "surveys/UPDATE",
  DUPLICATE_QUESTION_GROUP: "surveys/DUPLICATE_QUESTION_GROUP",
  DUPLICATE_QUESTION: "surveys/DUPLICATE_QUESTION",
  DELETE: "surveys/DELETE",
  DELETE_QUESTION_GROUP_BY_ID: "surveys/DELETE_QUESTION_GROUP_BY_ID",
  DELETE_QUESTION_BY_ID: "surveys/DELETE_QUESTION_BY_ID",
  RESTORE: "surveys/RESTORE",
  PERMANENTLY_DELETE: "surveys/PERMANENTLY_DELETE"
});
